name: SolsticeScotland
favicon: null
layout_spectrum: 0.49866
typography_spectrum: 0.75023
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0042ea'
    - '#4979f1'
    - '#cf83fc'
    - '#ab29f8'
  brandStrength: 0.25
  lightness: 0.5190155718009919
  saturation: 0.8327806140296161
  rhythmicContrast: 0.1469051220919937
purpose: []
