name: SolsticeScotland
favicon: null
layout_spectrum: 0.5207688054069877
typography_spectrum: 0.6770975093822926
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.13918755762279034
  lightness: 0.5190155718009919
  saturation: 0.8327806140296161
  rhythmicContrast: 0.1469051220919937
purpose: []
